[[questions]]
type = "ShortAnswer"
prompt.prompt = "Quelle commande est utilisée pour arrêter et supprimer tous les services définis dans un fichier Compose ?"
answer.answer = "docker compose down"
context = """
La commande `docker compose down` arrête tous les conteneurs et supprime également les réseaux et volumes définis dans le fichier Compose.
"""
id = "22025d3c-592a-4954-9116-3acf93e652ac"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Quel est le rôle de Docker Compose ?"
prompt.distractors = [
  "Construire des images Docker.",
  "Optimiser les performances des conteneurs.",
  "Résoudre les problèmes de réseau des conteneurs."
]
answer.answer = "Gérer les applications multi-conteneurs."
context = """
Docker Compose est utilisé pour définir et exécuter des applications comprenant plusieurs conteneurs via un fichier de configuration unique.
"""
id = "074fc5fe-ad5b-4be5-986d-98c41934054c"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Quel format de fichier est utilisé pour définir les configurations Docker Compose ?"
answer.answer = "YAML"
context = """
Docker Compose utilise le format YAML pour décrire les services, réseaux et volumes dans une application multi-conteneurs.
"""
id = "c2c1a02d-759a-4010-b3d8-cbb9cbc40ed6"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Quel fichier définit une configuration multi-conteneurs dans Docker Compose ?"
prompt.distractors = [
  "docker-compose.config",
  "docker.multi.yml",
  "docker-compose.json"
]
answer.answer = "docker-compose.yml"
context = """
Le fichier `docker-compose.yml` est le format standard utilisé pour décrire les services, réseaux et volumes dans Docker Compose.
"""
id = "c3bdf7d6-f766-4d8d-b736-40597fb7dc71"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Comment affichez-vous les journaux d’un service spécifique dans Docker Compose ?"
answer.answer = "docker compose logs <nom-service>"
context = """
La commande `docker compose logs <nom-service>` permet de consulter les journaux générés par un service spécifique.
"""
id = "e9fa4d52-d27a-4aea-b5be-f87bd33cd126"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Quelle commande est utilisée pour mettre à l’échelle un service à 3 instances avec Docker Compose ?"
prompt.distractors = [
  "docker compose scale --replicas=3",
  "docker compose up --instances=3",
  "docker compose up --scale=3"
]
answer.answer = "docker compose up --scale <nom-service>=3"
context = """
La commande `docker compose up --scale <nom-service>=3` permet de définir le nombre d’instances pour un service donné.
"""
id = "a9435bb4-a5e3-45d8-95f4-940c1764b4d4"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Quelle section dans le fichier `docker-compose.yml` est utilisée pour configurer des variables d’environnement ?"
prompt.distractors = [
  "env",
  "config",
  "variables"
]
answer.answer = "environment"
context = """
La section `environment` permet de définir des variables d’environnement accessibles dans un conteneur.
"""
id = "d36007be-bdb1-4500-9b44-b70ef3f06040"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Que fait la propriété `depends_on` dans un fichier Compose ?"
prompt.distractors = [
  "Configure un service pour attendre qu’un autre soit en bonne santé avant de démarrer.",
  "Crée des liens réseau entre les services.",
  "Redémarre automatiquement les services dépendants en cas d’échec."
]
answer.answer = "Spécifie l’ordre de démarrage des services."
context = """
La propriété `depends_on` détermine l’ordre dans lequel les services sont démarrés, mais ne garantit pas qu’un service soit prêt avant de lancer un autre.
"""
id = "af7877d4-6ad9-46b5-81f4-e74afa8c6e41"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Quelle propriété dans un fichier Compose est utilisée pour mapper un port du conteneur à un port de l’hôte ?"
answer.answer = "ports"
context = """
La propriété `ports` permet de définir le mapping entre un port interne au conteneur et un port externe sur l’hôte.
"""
id = "c6b83a07-31f1-488e-865b-14164365ce3f"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Quelle commande démarre une application multi-conteneurs définie dans un fichier Compose ?"
answer.answer = "docker compose up"
context = """
La commande `docker compose up` lit le fichier Compose et démarre tous les services définis.
"""
id = "2411074b-d9ce-4ff9-9616-5b9a4abc9eca"
