[[questions]]
type = "MultipleChoice"
prompt.prompt = "Quel mode réseau Docker offre une isolation réseau complète ?"
prompt.distractors = [
  "Bridge",
  "Host",
  "Overlay"
]
answer.answer = "None"
context = """
Le mode réseau `None` désactive complètement la connectivité réseau pour un conteneur, offrant une isolation totale.
"""
id = "44499283-5bbd-4dc8-9125-d079777d90a5"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Quel est le mode réseau par défaut pour les conteneurs autonomes Docker ?"
answer.answer = "bridge"
context = """
Le mode réseau `bridge` est utilisé par défaut, permettant aux conteneurs de communiquer avec l’hôte et entre eux via un pont réseau.
"""
id = "1f3b6fe9-dd15-44f9-a504-8f6fd7a0c926"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Quel est le but d’un réseau Docker personnalisé ?"
prompt.distractors = [
  "Limiter l'accès réseau aux ressources externes.",
  "Exécuter des conteneurs sans accès à Internet.",
  "Exposer les ports des conteneurs à l'hôte."
]
answer.answer = "Permettre la communication entre conteneurs via DNS."
context = """
Un réseau Docker personnalisé permet aux conteneurs de se découvrir et de communiquer entre eux grâce à des noms DNS.
"""
id = "f26566fa-9913-431e-bac9-55ebf900c718"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Quelle commande permet de déconnecter un conteneur d’un réseau Docker ?"
answer.answer = "docker network disconnect"
context = """
La commande `docker network disconnect` supprime la connexion d’un conteneur à un réseau sans arrêter le conteneur.
"""
id = "dfe4c1cb-77bf-4783-ab9e-d2871cd179d8"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Quelle commande permet de créer un réseau Docker personnalisé ?"
prompt.distractors = [
  "docker create network",
  "docker net init",
  "docker init --network"
]
answer.answer = "docker network create"
context = """
La commande `docker network create` permet de définir un réseau personnalisé avec des options spécifiques comme le driver ou le sous-réseau.
"""
id = "8ff76ee4-feb6-412a-813c-d9e5be484ba7"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Quelle commande inspecte la configuration réseau d’un conteneur ?"
prompt.distractors = [
  "docker network inspect",
  "docker net status",
  "docker ps"
]
answer.answer = "docker inspect"
context = """
La commande `docker inspect` fournit des détails complets sur un conteneur, y compris ses configurations réseau.
"""
id = "8e76669b-8515-427a-ade7-01b153cd58ed"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Quel flag est utilisé dans la commande `docker run` pour spécifier un réseau ?"
answer.answer = "--network"
context = """
Le flag `--network` permet de spécifier le réseau auquel le conteneur sera connecté lors de son démarrage.
"""
id = "39ace6f6-0dd3-4598-b0fa-a9287dd9501f"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Que se passe-t-il si vous exécutez deux conteneurs avec le même port exposé sur l’hôte sans spécifier de ports externes ?"
prompt.distractors = [
  "Les deux conteneurs fonctionneront sans problème.",
  "Docker attribuera automatiquement un port externe unique à chaque conteneur.",
  "Les conteneurs partageront dynamiquement le port."
]
answer.answer = "Docker affichera une erreur pour ports en conflit."
context = """
Docker n'autorise pas deux conteneurs à exposer le même port sur l’hôte sans configuration explicite des ports externes.
"""
id = "3483eda4-3b44-4900-a373-4d928d2f0512"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Quel est le driver par défaut utilisé lors de la création d’un réseau personnalisé ?"
answer.answer = "bridge"
context = """
Le driver `bridge` est utilisé par défaut pour les réseaux personnalisés, offrant une isolation et une connectivité de base.
"""
id = "51bc3ffe-ee7f-4516-85db-1140eea90388"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Qu’est-ce que Docker utilise pour la découverte de services dans les réseaux personnalisés ?"
answer.answer = "DNS"
context = """
Dans les réseaux personnalisés, Docker utilise un serveur DNS intégré pour permettre aux conteneurs de se découvrir via leurs noms.
"""
id = "160ce730-11a4-408e-9996-1bf92b868a76"
