[[questions]]
type = "MultipleChoice"
prompt.prompt = "Laquelle de ces commandes démarre un conteneur au premier plan ?"
prompt.distractors = [
  "docker start",
  "docker exec",
  "docker attach"
]
answer.answer = "docker run"
context = """
La commande `docker run` crée et démarre un nouveau conteneur au premier plan par défaut, sauf indication contraire.
"""
id = "a98cbf8c-0852-4e9c-9891-9fd46d308f4a"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Quel est le rôle du démon Docker ?"
answer.answer = "Le démon Docker gère les conteneurs et les images en arrière-plan, et il communique avec le client Docker via l'API."
context = """
Le démon Docker (dockerd) est un service système qui exécute et gère les conteneurs, surveillant les images et les volumes.
"""
id = "de0f74d8-0f6e-4686-b6f0-3a6541aa96d5"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Après avoir installé Docker, quelle commande permet de vérifier que l'installation a réussi ?"
prompt.distractors = [
  "docker -help",
  "docker ps",
  "docker status"
]
answer.answer = "docker --version"
context = """
La commande `docker --version` permet de vérifier la version installée de Docker et de s'assurer qu'il est correctement installé.
"""
id = "a75dabf8-b9ef-4895-82d7-eefbfb2781ba"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Quelle est la différence entre `docker ps` et `docker ps -a` ?"
answer.answer = "`docker ps` affiche uniquement les conteneurs en cours d'exécution, tandis que `docker ps -a` affiche tous les conteneurs, y compris ceux arrêtés."
context = """
La commande `docker ps` liste uniquement les conteneurs actifs, tandis que l'option `-a` (all) inclut tous les conteneurs créés, actifs ou inactifs.
"""
id = "8f1b9651-0bbf-41a8-bab2-c500d6e14e26"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Quel flag est utilisé pour exécuter un conteneur de manière interactive ?"
prompt.distractors = [
  "-d",
  "-rm",
  "-exec"
]
answer.answer = "-it"
context = """
Le flag `-it` combine `-i` (mode interactif) et `-t` (pseudo-terminal), permettant une interaction directe avec le conteneur.
"""
id = "bbf4f901-8310-4eee-b402-1f381c387d99"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Que se passe-t-il si vous exécutez `docker ps` sans aucun conteneur en cours d'exécution ?"
answer.answer = "La commande retourne un tableau vide avec seulement les en-têtes des colonnes."
context = """
Lorsque `docker ps` est utilisé sans conteneurs actifs, la sortie n'affiche rien d'autre que les colonnes `CONTAINER ID`, `IMAGE`, etc.
"""
id = "9acdbfdf-09ba-402e-ae3d-6b713d41de2e"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Quelle commande CLI liste toutes les images disponibles sur votre système local ?"
prompt.distractors = [
  "docker ps",
  "docker pull",
  "docker volume ls"
]
answer.answer = "docker images"
context = """
La commande `docker images` affiche toutes les images téléchargées et disponibles localement sur votre machine.
"""
id = "231d1d8e-1621-4a6a-816e-e2ed41a89da1"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Citez deux problèmes courants lors de l'installation de Docker et comment les résoudre."
answer.answer = """
1. Problème : Docker nécessite des privilèges d'administrateur. Solution : Ajoutez votre utilisateur au groupe Docker avec la commande `sudo usermod -aG docker <votre_utilisateur>`.
2. Problème : Le service Docker ne démarre pas. Solution : Redémarrez le service avec `sudo systemctl restart docker`.
"""
context = """
Lors de l'installation de Docker, les problèmes liés aux permissions ou au démarrage du service sont fréquents. Les solutions incluent la configuration du groupe Docker ou le redémarrage du démon.
"""
id = "a3116060-7dc6-4131-a0de-185154b17d9d"
