[[questions]]
type = "MultipleChoice"
prompt.prompt = "What is the primary use of Azure Virtual Machines (VMs)?"
prompt.distractors = [
  "To manage relational databases",
  "To deploy serverless code",
  "To store unstructured data"
]
answer.answer = "To run virtualized operating systems and applications"
context = """
Azure Virtual Machines (VMs) provide on-demand, scalable computing resources in the cloud. They are often used to host applications, test environments, and development workloads.
"""
id = "47aa218b-ba8d-46ef-9703-124101f120e8"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "What is the main advantage of Azure Virtual Machine Scale Sets?"
prompt.distractors = [
  "They provide serverless compute options.",
  "They automatically scale relational databases.",
  "They manage containerized workloads."
]
answer.answer = "They enable automatic scaling of virtual machines to handle varying workloads."
context = """
Azure Virtual Machine Scale Sets allow you to automatically increase or decrease the number of virtual machines based on current demand, ensuring high availability and performance.
"""
id = "41bbbffc-dc34-4d2e-9f93-8cf4102950fc"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "What is the main purpose of Azure Container Instances (ACI)?"
prompt.distractors = [
  "To create virtual machine clusters",
  "To deploy Kubernetes clusters",
  "To build large-scale serverless architectures"
]
answer.answer = "To run containers without needing to manage servers or orchestration"
context = """
Azure Container Instances (ACI) allow you to quickly and efficiently run containerized applications without requiring the overhead of virtual machines or Kubernetes orchestration.
"""
id = "902f19b7-c245-4070-86be-936a63b66a71"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Which Azure service is best for hosting web applications and RESTful APIs?"
prompt.distractors = [
  "Azure Virtual Machines",
  "Azure Container Instances",
  "Azure Functions"
]
answer.answer = "Azure App Service"
context = """
Azure App Service is a fully managed platform-as-a-service (PaaS) offering for hosting web applications, RESTful APIs, and mobile backends.
"""
id = "86314cc6-7197-4e6c-935a-a5c2363ce1bf"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "What is a key benefit of Azure Functions?"
prompt.distractors = [
  "They provide persistent virtual machines for hosting applications.",
  "They automatically scale virtual machines based on demand.",
  "They simplify managing containerized applications."
]
answer.answer = "They enable serverless execution of code triggered by events."
context = """
Azure Functions is a serverless compute service that allows you to run event-driven code without provisioning or managing infrastructure.
"""
id = "98c51125-a5d4-43ee-a221-e20dabe5b724"
